package:
  name: indexedconv
  version: "2.0.a"

source:
  git_rev: master
  git_url: https://github.com/IndexedConv/IndexedConv.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pytorch
    - tensorflow
    - numpy
    - matplotlib
    - tensorboardx
    - h5py

test:
  imports:
  - indexedconv

about:
  home: https://github.com/IndexedConv/IndexedConv
  license: MIT
  license_file: LICENSE